-- Append-only audit trail of assignment outcomes (accept/decline/timeout)
-- -- not written at assignment time, so it can't answer "how many chats
-- was this engineer assigned today" on its own.
CREATE TYPE chat_routing.assignment_outcome AS ENUM (
    'CONNECTED',
    'REJECTED',
    'TIMED_OUT'
);

CREATE TABLE chat_routing.chat_queue_engineer_assignment (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id       text NOT NULL REFERENCES chat_routing.chat_conversation (case_id) ON DELETE RESTRICT,
    engineer_id   text NOT NULL REFERENCES chat_routing.cs_engineer_status (user_id),
    status        chat_routing.assignment_outcome NOT NULL,
    occurred_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_chat_queue_engineer_assignment_case
    ON chat_routing.chat_queue_engineer_assignment (case_id, occurred_at);

CREATE INDEX idx_chat_queue_engineer_assignment_engineer
    ON chat_routing.chat_queue_engineer_assignment (engineer_id, occurred_at);
