-- Baseline: the chat_routing schema as of migration 000023 in
-- ../migrations/, split into one migration per table so it bootstraps a
-- brand-new database without replaying that whole 23-step history. Content
-- must match ../current_schema.sql -- regenerate both together (see
-- current_schema.sql's own header) whenever ../migrations/ gains a new
-- migration.
--
-- Only for a database that has never run ../migrations/. Do not point this
-- at a database that already has that history applied -- every object
-- below already exists there and every CREATE will fail. The two are
-- tracked separately on purpose: run this with its own
-- -x-migrations-table=chat_routing_schema_baseline_migrations, distinct
-- from ../migrations/'s own chat_routing_schema_migrations, so golang-migrate
-- can never confuse "ran the baseline" with "ran the real history" if the
-- same tool is later pointed at ../migrations/ against this same database.
--
-- Files after this one are ordered by foreign-key dependency, same as a
-- normal migration sequence: cs_engineer_status and work_item/comment have
-- no dependencies and come first; chat_conversation depends on both;
-- chat_queue and chat_queue_engineer_assignment depend on chat_conversation
-- and come last.

CREATE SCHEMA IF NOT EXISTS chat_routing;
