-- Copyright (c) 2026 WSO2 LLC. (https://www.wso2.com).
--
-- WSO2 LLC. licenses this file to you under the Apache License,
-- Version 2.0 (the "License"); you may not use this file except
-- in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.

-- Append-only audit trail of assignment outcomes (accept/decline/timeout)
-- -- not written at assignment time, so it can't answer "how many chats
-- was this engineer assigned today" on its own.
CREATE TYPE chat_routing.assignment_outcome AS ENUM (
    'CONNECTED',
    'REJECTED',
    'TIMED_OUT'
);

CREATE TABLE chat_routing.chat_queue_engineer_assignment (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id       text NOT NULL REFERENCES chat_routing.chat_conversation (case_id) ON DELETE RESTRICT,
    engineer_id   text NOT NULL REFERENCES chat_routing.cs_engineer_status (user_id),
    status        chat_routing.assignment_outcome NOT NULL,
    occurred_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_chat_queue_engineer_assignment_case
    ON chat_routing.chat_queue_engineer_assignment (case_id, occurred_at);

CREATE INDEX idx_chat_queue_engineer_assignment_engineer
    ON chat_routing.chat_queue_engineer_assignment (engineer_id, occurred_at);
